ELcomilon_django-main/TiendaStark/TiendaStark/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, reverse_lazy
from django.views.generic.base import RedirectView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('api/', include('rest_vehiculo.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ELcomilon_django-main/TiendaStark/core/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from django.contrib.auth import views as auth_views
from .views import home, administrar_productos, reportes, tienda, ficha, registro
from .views import iniciar_sesion, registrar_usuario, cerrar_sesion
from .views import perfil_usuario, iniciar_pago, pago_exitoso,reportes_usuarios
from .views import  index
from .views_poblar_bd import poblar_bd

urlpatterns = [
    path('', home, name="home"),
    path('index', index, name="index"),
    path('poblar_bd', poblar_bd, name="poblar_bd"),
    
    path('administrar_productos/<action>/<id>', administrar_productos, name="administrar_productos"),
    
    path('tienda', tienda, name="tienda"),
    path('ficha/<id>', ficha, name="ficha"),
    path('iniciar_sesion/', iniciar_sesion, name="iniciar_sesion"),
    path('cerrar_sesion/', cerrar_sesion, name='cerrar_sesion'),
    path('registrar_usuario/', registrar_usuario, name="registrar_usuario"),
    path('password_cambiada/', TemplateView.as_view(template_name='core/password_cambiada.html'), name='password_cambiada'),
    path('cambiar_password/', auth_views.PasswordChangeView.as_view(template_name='core/cambiar_password.html', success_url='/password_cambiada'), name='cambiar_password'),
    path('perfil_usuario/', perfil_usuario, name="perfil_usuario"),
    path('iniciar_pago/<id>', iniciar_pago, name="iniciar_pago"),
    path('pago_exitoso/', pago_exitoso, name="pago_exitoso"),
    path('registro/', registro, name="registro"),
    path('reportes/', reportes, name="reportes"),
    path('reportes_usuarios/', reportes_usuarios, name="reportes_usuarios"),
]

ELcomilon_django-main/TiendaStark/core/models.py
from django.db import models
from django.contrib.auth.models import User

class Categoria(models.Model):
    idCategoria = models.IntegerField(primary_key=True, verbose_name="Id de categoría")
    nombreCategoria = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre de la categoría")

    def __str__(self):
        return f"{self.idCategoria} - {self.nombreCategoria}"

class Productos(models.Model):
    patente = models.CharField(max_length=6, primary_key=True, verbose_name="ID")
    marca = models.CharField(max_length=80, blank=False, null=False, verbose_name="Servicio")
    modelo = models.CharField(max_length=80, null=True, blank=True, verbose_name="Tipo de servicio")
    imagen = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="Imagen")
    precio = models.DecimalField(max_digits=35, decimal_places=2, null=False, blank=False, verbose_name="Precio")
    estado = models.CharField(max_length=80, null=True, blank=True, verbose_name="Estado")
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)
    

    def __str__(self):
        return f"{self.patente} - {self.marca}, {self.modelo}"

class PerfilUsuario(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    

    def __str__(self):
        return f"{self.user.username} - {self.user.first_name} {self.user.last_name} ({self.user.email})"

class Ventas(models.Model):
    id_venta = models.AutoField(primary_key=True)
    orden_compra = models.IntegerField(null=True, blank=True)
    nombre = models.CharField(max_length=45)
    apellido = models.CharField(max_length=45)
    correo = models.CharField(max_length=70)
    monto = models.IntegerField(null=True, blank=True)
    estado = models.CharField(null=True ,max_length=70)
    fecha_compra = models.DateField(blank=True, null=True)

    def str(self):
        return f"{self.orden_compra} - {self.correo}"







class Productos2(models.Model):
    patente = models.CharField(max_length=6, primary_key=True, verbose_name="ID")
    marca = models.CharField(max_length=80, blank=False, null=False, verbose_name="Nombre Comida")
    modelo = models.CharField(max_length=80, null=True, blank=True, verbose_name="Tipo de servicio")
    imagen = models.ImageField(upload_to="images/", default="sinfoto.jpg", null=False, blank=False, verbose_name="Imagen")
    precio = models.DecimalField(max_digits=35, decimal_places=2, null=False, blank=False, verbose_name="Precio")
    estado = models.CharField(max_length=80, null=True, blank=True, verbose_name="Estado")
    categoria = models.ForeignKey(Categoria, on_delete=models.DO_NOTHING)

ELcomilon_django-main/TiendaStark/core/forms.py
from django import forms
from django.forms import ModelForm, fields, Form
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Productos, PerfilUsuario

class VehiculoForm(ModelForm):
    class Meta:
        model = Productos
        fields = ['patente', 'marca', 'modelo', 'imagen', 'precio','estado' , 'categoria']

class IniciarSesionForm(Form):
    username = forms.CharField(widget=forms.TextInput(), label="Usuario")
    password = forms.CharField(widget=forms.PasswordInput(), label="Contraseña")
    class Meta:
        fields = ['username', 'password']

class RegistrarUsuarioForm(UserCreationForm):
    
    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

class PerfilUsuarioForm(Form):
    first_name = forms.CharField(max_length=150, required=True, label="Nombres")
    last_name = forms.CharField(max_length=150, required=True, label="Apellidos")
    email = forms.CharField(max_length=254, required=True, label="Correo")
    

    class Meta:
        fields = '__all__'


class CustomUserForm(UserCreationForm):
    pass


        

ELcomilon_django-main/TiendaStark/core/views.py
from calendar import month
from email import message
from pyexpat.errors import messages
from typing import Awaitable
from datetime import date, datetime
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UsernameField
from django.contrib.auth.models import User
from django.shortcuts import redirect, render
from django.views.decorators.csrf import csrf_exempt
from django.urls import reverse_lazy
from .models import  Productos, PerfilUsuario, Ventas 
from .forms import  VehiculoForm, IniciarSesionForm
from .forms import RegistrarUsuarioForm, PerfilUsuarioForm,  CustomUserForm
#from .error.transbank_error import TransbankError
from transbank.webpay.webpay_plus.transaction import Transaction, WebpayOptions
from django.core.files.storage import FileSystemStorage
from django.http import HttpResponse
from django.template.loader import get_template
import random

def home(request):
    return render(request, "core/home.html")

def index(request):
    return render(request, "core/index.html")

def iniciar_sesion(request):
    data = {"mesg": "", "form": IniciarSesionForm()}

    if request.method == "POST":
        form = IniciarSesionForm(request.POST)
        if form.is_valid:
            username = request.POST.get("username")
            password = request.POST.get("password")
            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect(home)
                else:
                    data["mesg"] = "¡La cuenta o la password no son correctos!"
            else:
                data["mesg"] = "¡La cuenta o la password no son correctos!"
    return render(request, "core/iniciar_sesion.html", data)

def cerrar_sesion(request):
    logout(request)
    return redirect(home)

def tienda(request):
    data = {"list": Productos.objects.all().order_by('patente')}
    return render(request, "core/tienda.html", data)

#https://www.transbankdevelopers.cl/documentacion/como_empezar#como-empezar
#https://www.transbankdevelopers.cl/documentacion/como_empezar#codigos-de-comercio
#https://www.transbankdevelopers.cl/referencia/webpay

# Tipo de tarjeta   Detalle                        Resultado
#----------------   -----------------------------  ------------------------------
# VISA              4051885600446623
#                   CVV 123
#                   cualquier fecha de expiración  Genera transacciones aprobadas.
# AMEX              3700 0000 0002 032
#                   CVV 1234
#                   cualquier fecha de expiración  Genera transacciones aprobadas.
# MASTERCARD        5186 0595 5959 0568
#                   CVV 123
#                   cualquier fecha de expiración  Genera transacciones rechazadas.
# Redcompra         4051 8842 3993 7763            Genera transacciones aprobadas (para operaciones que permiten débito Redcompra y prepago)
# Redcompra         4511 3466 6003 7060            Genera transacciones aprobadas (para operaciones que permiten débito Redcompra y prepago)
# Redcompra         5186 0085 4123 3829            Genera transacciones rechazadas (para operaciones que permiten débito Redcompra y prepago)

@csrf_exempt
def iniciar_pago(request, id):
    print("Webpay Plus Transaction.create")
    buy_order = str(random.randrange(1000000, 99999999))
    session_id = request.user.username
    amount = Productos.objects.get(patente=id).precio
    return_url = 'http://127.0.0.1:8000/pago_exitoso/'

    # response = Transaction.create(buy_order, session_id, amount, return_url)
    commercecode = "597055555532"
    apikey = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"

    tx = Transaction(options=WebpayOptions(commerce_code=commercecode, api_key=apikey, integration_type="TEST"))
    response = tx.create(buy_order, session_id, amount, return_url)
    print(response['token'])

    

    context = {
        "buy_order": buy_order,
        "session_id": session_id,
        "amount": amount,
        "return_url": return_url,
        "response": response,
        "token_ws": response['token'],
        "url_tbk": response['url'],
        "first_name": request.user.first_name,
        "last_name": request.user.last_name,
        "email": request.user.email,
        
    }

    return render(request, "core/iniciar_pago.html", context)

@csrf_exempt
def pago_exitoso(request):

    if request.method == "GET":
        token = request.GET.get("token_ws")
        print("commit for token_ws: {}".format(token))
        commercecode = "597055555532"
        apikey = "579B532A7440BB0C9079DED94D31EA1615BACEB56610332264630D42D0A36B1C"
        tx = Transaction(options=WebpayOptions(commerce_code=commercecode, api_key=apikey, integration_type="TEST"))
        response = tx.commit(token=token)
        print("response: {}".format(response))

        user = User.objects.get(username=response['session_id'])
        form = PerfilUsuarioForm()

        context = {
            "buy_order": response['buy_order'],
            "session_id": response['session_id'],
            "amount": response['amount'],
            "response": response,
            "token_ws": token,
            "first_name": user.first_name,
            "last_name": user.last_name,
            "email": user.email,
            "response_code": response['response_code']
        }
#Enviar info. de registro de compra
        registrar_venta(context["buy_order"], user.first_name, user.last_name, context["email"], context["amount"])
            
        return render(request, "core/pago_exitoso.html", context)
    else:
        return redirect(home)
    
#METODO DE REGISTRO
@csrf_exempt
def registrar_venta(orden, nombre, apellido, correo, monto):

    nueva_venta = Ventas()
    nueva_venta.orden_compra = orden
    nueva_venta.nombre = nombre
    nueva_venta.apellido = apellido
    nueva_venta.correo = correo
    nueva_venta.monto = monto
    nueva_venta.fecha_compra = date.today()
    nueva_venta.save()

    return nueva_venta

@csrf_exempt
def ficha(request, id):
    data = {"mesg": "", "producto": None}

    if request.method == "POST":
        if request.user.is_authenticated and not request.user.is_staff:
            return redirect(iniciar_pago, id)
        else:
            data["mesg"] = "¡Para poder comprar debe iniciar sesión como cliente!"

    data["producto"] = Productos.objects.get(patente=id)
    return render(request, "core/ficha.html", data)
 
@csrf_exempt
def administrar_productos(request, action, id):
    if not (request.user.is_authenticated and request.user.is_staff):
        return redirect(home)

    data = {"mesg": "", "form": VehiculoForm, "action": action, "id": id, "formsesion": IniciarSesionForm}

    if action == 'ins':
        if request.method == "POST":
            form = VehiculoForm(request.POST, request.FILES)
            if form.is_valid:
                try:
                    form.save()
                    data["mesg"] = "¡El producto fue creado correctamente!"
                except:
                    data["mesg"] = "¡No se pueden crear dos producto con la misma id!"

    elif action == 'upd':
        objeto = Productos.objects.get(patente=id)
        if request.method == "POST":
            form = VehiculoForm(data=request.POST, files=request.FILES, instance=objeto)
            if form.is_valid:
                form.save()
                data["mesg"] = "¡El producto fue actualizado correctamente!"
        data["form"] = VehiculoForm(instance=objeto)

    elif action == 'del':
        try:
            Productos.objects.get(patente=id).delete()
            data["mesg"] = "¡El producto fue eliminado correctamente!"
            return redirect(administrar_productos, action='ins', id = '-1')
        except:
            data["mesg"] = "¡El producto ya estaba eliminado!"

    data["list"] = Productos.objects.all().order_by('patente')
    return render(request, "core/administrar_productos.html", data)

def registrar_usuario(request):
    data = {
        'form': CustomUserForm()
    }
    
    if request.method == 'POST':
        form = RegistrarUsuarioForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data['username']
            rut = request.POST.get("rut")
            direccion = request.POST.get("direccion")
            user = authenticate(username = form.cleaned_data["username"], password=form.cleaned_data["password1"])
            return redirect(iniciar_sesion)
    form = RegistrarUsuarioForm()
    data["form"] = form
    return render(request, "core/registrar_usuario.html", context={'form': form})

def perfil_usuario(request):
    data = {"mesg": "", "form": PerfilUsuarioForm}

    if request.method == 'POST':
        form = PerfilUsuarioForm(request.POST)
        if form.is_valid():
            user = request.user
            user.first_name = request.POST.get("first_name")
            user.last_name = request.POST.get("last_name")
            user.email = request.POST.get("email")
            user.save()
            data["mesg"] = "¡Sus datos fueron actualizados correctamente!"

    
    form = PerfilUsuarioForm()
    form.fields['first_name'].initial = request.user.first_name
    form.fields['last_name'].initial = request.user.last_name
    form.fields['email'].initial = request.user.email
    data["form"] = form
    return render(request, "core/perfil_usuario.html", data)


def registro(request):
    data = {
        'form': CustomUserForm()
    }
    
    if request.method == 'POST':
        form = CustomUserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username = form.cleaned_data["username"], password=form.cleaned_data["password1"])
            login(request, user)

ELcomilon_django-main/TiendaStark/core/templates/core/administrar_productos.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
<link href="{% static 'core/css/forms.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/home.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
<h1>Administrar Servicios</h1>
{% if form %}
<form method="POST" action="" enctype="multipart/form-data" id="formulario">
    <div class="form-group" style="color:black !important;">
        {% csrf_token %} {{ form.as_ul }}
        {% if action == 'upd'  %}
            <script>
                $(document).ready(function() {
                    $('#id_patente').attr('readonly', true);
                });
            </script>
        {% endif %}

    </div>
    <input style="width: auto;" type="submit" class="btn btn-primary btnwidth" id="id_guardar" value="Guardar">
    <a style="width: auto;" class="btn btn-success btnwidth" href="{% url 'administrar_productos' 'ins' -1 %}">Nuevo</a>
    {% if id != '-1' %}
    <a style="width: auto;" class="btn btn-danger btnwidth" href="{% url 'administrar_productos' 'del' id %}">Eliminar</a>
    {% endif %}
    <a style="width: auto;" class="btn btn-info btnwidth" href="{% url 'home' %}">Inicio</a>
    {% if mesg %}
    <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
    {% endif %}
</form>
{% endif %}
{% if list %}
<table id="tabla_datos" class="texto-negro" style="color:black !important;">
    <thead>
        <tr>
            <th>ID</th>
            <th>Servicio</th>
            <th>Tipo de servicio</th>
            <th>Imagen</th>
            <th>Precio</th>
            <th>Estado</th>
            <th>Categoría</th>
            <th class="titulo_boton">Editar</th>
            <th class="titulo_boton">Eliminar</th>
        </tr>
    </thead>
    <tbody>
        {% for ve in list %}
        <tr>
            <td>{{ ve.patente }}</td>
            <td>{{ ve.marca }}</td>
            <td>{{ ve.modelo }}</td>
            <td><img src="/media/{{ ve.imagen }}" class="mini_auto" alt=""></td>
            <td>{{ ve.precio }}</td>
            <td>{{ ve.estado }}</td>
            <td>{{ ve.categoria }}</td>
            <td><a href="{% url 'administrar_productos' 'upd' ve.patente %}" 
                class="btn btn-primary btn-sm boton_chico"
                style="width: auto;">Editar</a></td>
            <td><a href="{% url 'administrar_productos' 'del' ve.patente %}" 
                class="btn btn-danger btn-sm boton_chico"
                style="width: auto;">Eliminar</a></td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endif %}
<br>
{% endblock content %}

ELcomilon_django-main/TiendaStark/core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
        <title>SERVIEXPRESS</title>
    {% endblock %}
    <link rel="stylesheet" href="{% static 'core/css/base.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
    {% block stylesheet %} {% endblock %}
</head>
<body>
    {% block navbar %}
        <script>
            $(document).ready(function(){
                set_nav_li("#inicio", "{% url 'home' %}", "{% static 'core/img/home.png' %}");
                set_nav_li("#tienda", "{% url 'tienda' %}", "{% static 'core/img/shop.png' %}");
                set_nav_li("#admsis", "{% url 'admin:index' %}", "{% static 'core/img/cohete.png' %}");
                set_nav_li("#manpro", "{% url 'administrar_productos' 'ins' '-1' %}", "{% static 'core/img/man.png' %}");
                set_nav_li("#regist", "{% url 'registrar_usuario' %}", "{% static 'core/img/registro.png' %}");
                set_nav_li("#inises", "{% url 'iniciar_sesion' %}", "{% static 'core/img/login.png' %}");
                set_nav_li("#cerses", "{% url 'cerrar_sesion' %}", "{% static 'core/img/login.png' %}");
                set_nav_li("#perfil", "{% url 'perfil_usuario' %}", "{% static 'core/img/user.png' %}");
                set_nav_li("#chpass", "{% url 'cambiar_password' %}", "{% static 'core/img/password.png' %}");
                set_nav_li("#reportes", "{% url 'reportes' %}", "{% static 'core/img/reporte.png' %}");

                function set_nav_li(id, url, img) {
                    $(id).addClass('nav-item list-inline-item align-center nav_item_text');
                    name = $(id).html();
                    $(id).html('');
                    $(id).append(`<a href="${url}"><img class="img_menu" src="${img}">${name}</a>`)
                }
            });
        </script>
        <nav id="navbar">
            <div id="nav">
                <ul class="list-inline">
                    <!-- inicio menú para usuarios anónimos -->
                    <li id="inicio">Inicio</li>    
                    <li id="tienda">Servicios</li>
                    <!-- fin menú para usuarios anónimos -->

                    {% if user.is_authenticated and user.is_staff %}
                        <li id="admsis">Administrar sistema</li>
                        <li id="manpro">Mantenedor de servicios</li>
                        <li id="reportes">Reportes</li>
                    {% endif %}
                    
                    {% if not user.is_authenticated and not user.is_staff %}
                        <li id="regist">Registrarme</li>
                    {% endif %}
                    
                    {% if not user.is_authenticated %}
                        <li id="inises">Iniciar sesión</li>
                    {% endif %}

                    {% if user.is_authenticated %}
                        <li id="chpass">Cambiar contraseña</li>
                        <li id="cerses">Cerrar sesión</li>
                        <li id="perfil">{{ user.get_full_name }}</li>
                    {% endif %}
                    
                </ul>
            </div>                                 
        </nav>
        
    {% endblock %}


    

    <div class="content container">
        {% block content %}{% endblock %}
    </div>

</body>




</html>

ELcomilon_django-main/TiendaStark/core/templates/core/cambiar_password.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/cambiar_password.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %} 
    <h1>Cambiar Contraseña</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 borde_formulario">
                <form method="POST">
                    <div class="centrar texto-negro" style="color:black !important;">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <input type="submit" class="btn btn-primary" value="Cambiar contraseña">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

ELcomilon_django-main/TiendaStark/core/templates/core/ficha.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/forms.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <h1>Tienda El Comilon</h1>
    <div class="container-fluid">
        <div class="row text-center">
            <div class="mx-auto col-sm-12 col-md-6 col-lg-6 col-xl-6 ficha_auto_recuadro">
                <img src="/media/{{ producto.imagen }}" class="ficha_auto_imagen" alt="">
            </div>
            <div class="mx-auto col-sm-12 col-md-6 col-lg-6 col-xl-6 ficha_datos_recuadro">
                <h2>
                    Nombre: {{ producto.marca }}<br><br>
                </h1>
                <h2>
                    Tipo de servicio: {{ producto.modelo }}
                </h2>
                <h2>
                    Precio: {{ producto.precio }}
                </h2>
                <br>
                <form method="POST">
                    <input type="submit" class="btn btn-primary" value="Comprar">
                    {% if mesg %}
                        <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
                    {% endif %}
                </form>
            </div>
        </div>
    </div>
    <div style="margin-top: 20px; text-align: center;">
        <a href="{% url 'tienda' %}" class="btn btn-info btn-sm">Ir a la tienda</a>&nbsp;&nbsp;&nbsp;
        <a href="{% url 'home' %}" class="btn btn-info btn-sm">Ir a la página de inicio</a>
    </div>
{% endblock content %}

ELcomilon_django-main/TiendaStark/core/templates/core/iniciar_pago.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/iniciar_sesion.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <h1>Iniciar Proceso de Pago</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-6 borde_formulario">
                <form method="POST" action="{{ url_tbk }}">
                    <div class="centrar texto-negro" style="color:black !important;">
                        {% csrf_token %}

                        Número de Orden de Compra: {{ buy_order }}<br><br>
                        Nombre cliente: {{ first_name }} {{ last_name }}<br><br>
                        Correo electrónico: {{ email }}<br><br>
                        Monto a Pagar: {{ amount }}<br><br>

                        <input type="hidden" name="token_ws" value="{{ token_ws }}" />
                        <input type="submit" class="btn btn-primary" value="Ir a pagar">
                        {% if mesg %}
                        <div id="form_message" class="alert alert-danger" role="alert">{{ mesg }}</div>
                        {% endif %}
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock content %}

ELcomilon_django-main/TiendaStark/core/templates/core/pago_exitoso.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/iniciar_sesion.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    {% if response_code == 0 %}
        <h1>¡El Pago fue Realizado con Exito!</h1>
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-6 borde_formulario text-center" style="color:black !important;">
                    {% csrf_token %}

                    Número de Orden de Compra: {{ buy_order }}<br><br>
                    Nombre cliente: {{ first_name }} {{ last_name }}<br><br>
                    Correo electrónico: {{ email }}<br><br>
                    Monto a Pagar: {{ amount }}<br><br>

                    <a href="{% url 'tienda' %}" class="btn btn-info btn-sm">Ir a la tienda</a>
                </div>
            </div>
        </div>
    {% else %}
        <h1>¡El Pago no Pudo ser Realizado con Exito!<br>Por Favor Intente Nuevamente Más Tarde...</h1>
    {% endif %}
{% endblock content %}

ELcomilon_django-main/TiendaStark/core/templates/core/password_cambiada.html
{% extends 'core/base.html' %}
{% load static %}

{% block stylesheet %}
    <link href="{% static 'core/css/password_cambiada.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/style.css'%}" rel="stylesheet">
    <link href="{% static 'core/css/bootstrap.min.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container justify-content-center align-center col-sm-8">
        <h1>¡El cambio de contraseña fue realizado con éxito!</h1>
    </div>
{% endblock content %}